services:
  app:
    build:
      context: ./docker/php
    container_name: laravel_app
    restart: always
    working_dir: /var/www
    volumes:
      - .:/var/www
    depends_on:
      - postgres
    networks:
      - laravel_red_solidaria
  
  nginx:
    image: nginx:latest
    container_name: laravel_nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - .:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/certs:/etc/nginx/certs
    depends_on:
      - app
    networks:
      - laravel_red_solidaria


  postgres: 
    image: postgres:16.8
    container_name: laravel_postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_USER: laravel_user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: solidaria
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - laravel_red_solidaria
  
  adminer:
    image: adminer:latest
    container_name: laravel_adminer
    restart: always
    ports:
      - "8080:8080"
    networks:
      - laravel_red_solidaria
  node:
    image: node:22
    container_name: laravel_node
    working_dir: /var/www
    volumes:
      - .:/var/www
    command: bash -c "npm install && npm run dev"
    ports:
      - "5173:5173"
    networks:
      - laravel_red_solidaria
  
  composer:
    build:
      context: ./docker/php
    container_name: laravel_composer
    working_dir: /var/www
    volumes:
      - .:/var/www
    entrypoint: ["composer"]
    networks:
      - laravel_red_solidaria

networks:
  laravel_red_solidaria:

volumes:
  postgres_data: